#file: noinspection SpringBootApplicationYaml
#port- ??? 8080
server:
  port: 9003

# mysql
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://db-jbnmu-kr.vpc-pub-cdb.ntruss.com:3306/studydb?serverTimezone=Asia/Seoul
    username: study
    password: bitcamp123!@#

  # mybatis
  mybatis:
    type-aliases-package: data.dto
    mapper-locations:
      - /mapper/**/*.xml