-------------- CREATE TABLE
CREATE TABLE USER_INFO (
  ID 		VARCHAR(20) 	PRIMARY KEY 						COMMENT'유저 아이디',
  PASSWORD 	VARCHAR(255) 	NOT NULL							COMMENT'유저 비밀번호',
  NAME 		VARCHAR(50)		NOT NULL							COMMENT'유저 이름',
  GENDER	VARCHAR(1)		NOT NULL							COMMENT'유저 성별 F:여자 / M: 남자', 
  NICKNAME 	VARCHAR(20)		NOT NULL 							COMMENT'유저 닉네임',
  ADDRESS 	VARCHAR(100)	NOT NULL							COMMENT'유저 주소',
  EMAIL		VARCHAR(100)	NOT NULL							COMMENT'유저 이메일',
  PHONE		VARCHAR(20)		NOT NULL							COMMENT'유저 핸드폰번호',
  JUMIN		VARCHAR(15)		NOT NULL							COMMENT'유저 주민등록번호',
  SIGN_DT	TIMESTAMP		NOT NULL DEFAULT CURRENT_TIMESTAMP 	COMMENT'유저 가입날짜'
);
-------------- ALTER TABLE
ALTER TABLE USER_INFO MODIFY SIGN_DATE TIMESTAMP COMMENT '유저 가입날짜' ; 
-------------- DROP TABLE
DROP TABLE USER_INFO;